# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-10 13:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(db_column='db_name', max_length=64, verbose_name='\u6570\u636e\u5e93\u540d\u79f0')),
                ('db_cn_name', models.CharField(max_length=64, verbose_name='\u6570\u636e\u5e93\u4e2d\u6587\u540d\u79f0')),
                ('warehouse_dir', models.TextField(blank=True, default='hdfs://NameNodeHACluster/apps/hive/warehouse', verbose_name='\u96c6\u7fa4\u9ed8\u8ba4\u8def\u5f84')),
                ('database_hdfs', models.CharField(default='db', max_length=128, verbose_name='\u6570\u636e\u5e93hdfs\u914d\u7f6e\u8def\u5f84')),
                ('eff_flag', models.CharField(choices=[('0', '\u5931\u6548'), ('1', '\u751f\u6548')], default='1', max_length=16, verbose_name='\u662f\u5426\u751f\u6548')),
                ('remark', models.TextField(blank=True, default='', verbose_name='\u6570\u636e\u5e93\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default='1', on_delete=models.SET(modelApp.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
            ],
            options={
                'db_table': 'integ_db',
                'verbose_name': '\u6570\u636e\u5e93',
            },
        ),
        migrations.CreateModel(
            name='DatabaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type_name', models.CharField(db_column='db_name', max_length=64, unique=True, verbose_name='\u6570\u636e\u5e93\u7c7b\u578b')),
                ('remark', models.TextField(blank=True, default='', verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default='1', on_delete=models.SET(modelApp.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
            ],
            options={
                'db_table': 'integ_db_type',
                'verbose_name': '\u6570\u636e\u5e93\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields_type', models.CharField(max_length=64, verbose_name='\u5b57\u6bb5\u7c7b\u578b')),
                ('remark', models.TextField(blank=True, default='', verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default='1', on_delete=models.SET(modelApp.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
                ('db_type', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='modelApp.DatabaseType', verbose_name='\u6570\u636e\u5e93\u7c7b\u578b')),
            ],
            options={
                'db_table': 'integ_fieldtype',
                'verbose_name': '\u5b57\u6bb5\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tb_name', models.CharField(max_length=64, verbose_name='\u8868\u540d\u79f0')),
                ('tb_cn_name', models.CharField(max_length=64, verbose_name='\u8868\u4e2d\u6587\u540d\u79f0')),
                ('tb_job', models.CharField(blank=True, max_length=64, verbose_name='\u8868\u4f5c\u4e1a\u540d\u79f0')),
                ('manage_external_flag', models.CharField(choices=[('-1', '\u5176\u4ed6'), ('0', '\u7ba1\u7406\u8868'), ('1', '\u5916\u90e8\u8868')], default='1', max_length=16, verbose_name='\u7ba1\u7406\u5916\u90e8\u8868\u6807\u5fd7')),
                ('partition_flag', models.CharField(choices=[('-1', '\u5176\u4ed6'), ('0', '\u975e\u5206\u533a\u8868'), ('1', '\u662f\u5206\u533a\u8868')], default='1', max_length=16, verbose_name='\u662f\u5426\u5206\u533a')),
                ('sd_flag', models.CharField(choices=[('-1', '\u5176\u4ed6'), ('0', '\u589e\u91cf'), ('1', '\u5168\u91cf')], default='1', max_length=16, verbose_name='\u5168\u91cf/\u589e\u91cf')),
                ('static_flag', models.CharField(choices=[('0', '\u5426'), ('1', '\u662f')], default='0', max_length=16, verbose_name='\u662f\u5426\u9759\u6001\u7ef4\u8868')),
                ('secret_level', models.CharField(choices=[('0', 'S0'), ('1', 'S1'), ('2', 'S2'), ('3', 'S3')], default='1', max_length=16, verbose_name='\u673a\u5bc6\u7a0b\u5ea6')),
                ('import_level', models.CharField(choices=[('0', 'P0'), ('1', 'P1'), ('2', 'P2'), ('3', 'P3'), ('4', 'P4')], default='2', max_length=16, verbose_name='\u91cd\u8981\u7a0b\u5ea6')),
                ('time_granularity', models.CharField(choices=[('0', '\u65e0'), ('1', '\u79d2'), ('2', '\u5206\u949f'), ('3', '\u5c0f\u65f6'), ('4', '\u5929'), ('5', '\u6708'), ('6', '\u5e74')], default='4', max_length=16, verbose_name='\u65f6\u95f4\u7c92\u5ea6')),
                ('life_cycle', models.CharField(choices=[('0', '\u672a\u5b9a'), ('1', '\u4e00\u5929'), ('2', '\u4e00\u5468'), ('3', '\u4e00\u6708'), ('4', '\u4e09\u6708'), ('5', '\u534a\u5e74'), ('6', '\u4e00\u5e74'), ('7', '\u4e09\u5e74'), ('8', '\u4e94\u5e74'), ('9', '\u6c38\u4e45')], default='7', max_length=16, verbose_name='\u751f\u547d\u5468\u671f')),
                ('hdfsfile', models.CharField(blank=True, max_length=128, verbose_name='HDFS\u8def\u5f84')),
                ('table_author', models.CharField(blank=True, max_length=128, verbose_name='\u8d1f\u8d23\u4eba')),
                ('state_flag', models.CharField(choices=[('\u5f00\u53d1\u4e2d', '\u5f00\u53d1\u4e2d'), ('\u6d4b\u8bd5\u4e2d', '\u6d4b\u8bd5\u4e2d'), ('\u5df2\u4e0a\u7ebf', '\u5df2\u4e0a\u7ebf'), ('\u5df2\u4e0b\u7ebf', '\u5df2\u4e0b\u7ebf'), ('\u5176\u4ed6', '\u5176\u4ed6')], default='\u5f00\u53d1\u4e2d', max_length=16, verbose_name='\u8868\u72b6\u6001')),
                ('eff_flag', models.CharField(choices=[('0', '\u65e0\u6548'), ('1', '\u6709\u6548')], default='1', max_length=16, verbose_name='\u662f\u5426\u6709\u6548')),
                ('source_key', models.CharField(blank=True, max_length=128, verbose_name='\u5bf9\u5e94\u6570\u636e\u6e90Key')),
                ('source_db', models.CharField(blank=True, max_length=128, verbose_name='\u5bf9\u5e94\u6e90\u6570\u636e\u5e93')),
                ('source_table', models.CharField(blank=True, max_length=128, verbose_name='\u5bf9\u5e94\u6e90\u6570\u636e\u8868')),
                ('source_author', models.CharField(blank=True, max_length=128, verbose_name='\u6570\u636e\u6e90\u5bf9\u63a5\u4eba')),
                ('job_source_dir', models.CharField(blank=True, max_length=128, verbose_name='\u4f5c\u4e1a\u5b58\u653e\u8def\u5f84\u540d\u79f0')),
                ('table_detail', models.TextField(blank=True, default='', verbose_name='\u8868\u6ce8\u91ca(\u8ba1\u7b97\u903b\u8f91&\u4e1a\u52a1\u8bf4\u660e)')),
                ('tb_job_script', models.TextField(blank=True, default='', verbose_name='\u811a\u672c\u4ee3\u7801')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default='1', on_delete=models.SET(modelApp.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
                ('db_name_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='modelApp.Database', verbose_name='\u6570\u636e\u5e93\u540d\u79f0')),
            ],
            options={
                'db_table': 'integ_table',
                'verbose_name': '\u8868',
            },
        ),
        migrations.CreateModel(
            name='TableLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_level_name', models.CharField(db_column='table_level_name', max_length=64, unique=True, verbose_name='\u8868\u5c42\u6b21\u540d\u79f0')),
                ('table_level_cn_name', models.CharField(db_column='table_level_cn_name', max_length=64, unique=True, verbose_name='\u8868\u5c42\u6b21\u4e2d\u6587\u540d\u79f0')),
                ('table_level_describe', models.TextField(blank=True, default='', verbose_name='\u8bf4\u660e')),
                ('table_level_example', models.TextField(blank=True, default='', verbose_name='\u4e3e\u4f8b')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'integ_tblevel',
                'verbose_name': '\u5c42\u6b21\u7ed3\u6784',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_theme_name', models.CharField(db_column='table_theme_name', max_length=64, unique=True, verbose_name='\u4e3b\u9898\u540d\u79f0')),
                ('table_theme_cn_name', models.CharField(db_column='table_theme_cn_name', max_length=64, unique=True, verbose_name='\u4e3b\u9898\u4e2d\u6587\u540d\u79f0')),
                ('table_theme_describe', models.TextField(blank=True, default='', verbose_name='\u8bf4\u660e')),
                ('remark', models.TextField(blank=True, default='', verbose_name='\u5907\u6ce8')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default='1', on_delete=models.SET(modelApp.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
            ],
            options={
                'db_table': 'integ_tbtheme',
                'verbose_name': '\u8868\u4e3b\u9898',
            },
        ),
        migrations.AddField(
            model_name='table',
            name='table_level',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='modelApp.TableLevel', verbose_name='\u5c42\u6b21\u7ed3\u6784'),
        ),
        migrations.AddField(
            model_name='table',
            name='table_theme',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='modelApp.Theme', verbose_name='\u8868\u4e3b\u9898'),
        ),
        migrations.AddField(
            model_name='database',
            name='db_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='modelApp.DatabaseType', verbose_name='\u6570\u636e\u5e93\u7c7b\u578b'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=set([('db_name_id', 'tb_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='fieldtype',
            unique_together=set([('db_type', 'fields_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='database',
            unique_together=set([('db_type', 'db_name')]),
        ),
    ]
