# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-18 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields_rank', models.IntegerField(verbose_name='\u5b57\u6bb5\u5e8f\u53f7')),
                ('fields_name', models.CharField(max_length=128, verbose_name='\u5b57\u6bb5\u540d\u79f0')),
                ('fields_cn_name', models.CharField(max_length=128, verbose_name='\u5b57\u6bb5\u89e3\u91ca')),
                ('partition_flag', models.CharField(choices=[('1', '\u662f'), ('0', '\u5426')], default='0', max_length=16, verbose_name='\u662f\u5426\u5206\u533a\u5b57\u6bb5')),
                ('fields_detail', models.TextField(blank=True, default='\u6765\u6e90\u8868\u548c\u5b57\u6bb5:', verbose_name='\u5b57\u6bb5\u89c4\u5219')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('fields_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelApp.FieldType', verbose_name='\u5b57\u6bb5\u7c7b\u578b')),
                ('tb_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelApp.Table', verbose_name='\u6240\u5c5e\u8868')),
            ],
            options={
                'db_table': 'integ_fields',
                'verbose_name': '\u5b57\u6bb5',
            },
        ),
        migrations.AlterUniqueTogether(
            name='fields',
            unique_together=set([('tb_name_id', 'fields_rank')]),
        ),
    ]
